# Site settings
title: 杨根威的博客
motto: 生于偶然 立于价值
email: 324097191@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.yanggenwei.com" # the base hostname & protocol for your site
twitter_username:
github_username:  yanggenwei

# Build settings
markdown: kramdown
